name: app_environment
channels:
  - snowflake
dependencies:
  - matplotlib=3.10.0
  - plotly=6.0.1
  - python=3.11.*
  - snowflake-ml-python=1.8.3
  - snowflake-snowpark-python=
  - snowflake.core=1.5.1
  - streamlit=
  - wordcloud=1.9.4
